# Generated by Django 4.2.7 on 2023-12-03 15:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lsd5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=5179)),
                ('차수', models.IntegerField(blank=True, null=True)),
                ('경위', models.CharField(blank=True, null=True)),
                ('사육두수', models.IntegerField(blank=True, null=True)),
                ('신고일', models.IntegerField(blank=True, null=True)),
                ('확진일', models.IntegerField(blank=True, null=True)),
                ('신고일_f', models.DateField(blank=True, null=True)),
                ('확진일_f', models.DateField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, db_column='X', null=True)),
                ('y', models.FloatField(blank=True, db_column='Y', null=True)),
                ('px', models.FloatField(blank=True, null=True)),
                ('py', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LSD_5179_CSV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SD_5179',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=5179)),
                ('ctprvn_cd', models.CharField(blank=True, max_length=2, null=True)),
                ('ctp_eng_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('ctp_kor_nm', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': '전국_시도_5179',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('srid', models.IntegerField()),
                ('precision', models.FloatField()),
                ('hasz', models.BooleanField()),
            ],
            options={
                'db_table': 'topology',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('topology', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LSD.topology')),
                ('layer_id', models.IntegerField()),
                ('schema_name', models.CharField()),
                ('table_name', models.CharField()),
                ('feature_column', models.CharField()),
                ('feature_type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('child_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'layer',
                'managed': False,
            },
        ),
    ]
